# Generated by Django 5.0.2 on 2024-10-24 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(upload_to='products/')),
                ('short_desc', models.CharField(max_length=500)),
                ('detailed_desc', models.TextField()),
                ('category', models.CharField(choices=[('Traditional Classics', 'Traditional Classics'), ('Barfis', 'Barfis'), ('Chocolate Specialties', 'Chocolate Specialties'), ('Kheer and Kheer Kadam', 'Kheer Kadam'), ('Namkeen and Snacks', 'Namkeen and Snacks'), ('Chikkis', 'Chikkis')], max_length=50)),
                ('is_exclusive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
