# Generated by Django 5.0.2 on 2024-10-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ingredients',
            field=models.TextField(default=None),
        ),
    ]
