# Generated by Django 5.0.2 on 2024-11-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='quantity',
        ),
    ]
