# Generated by Django 5.0.2 on 2024-11-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.site_users'),
            preserve_default=False,
        ),
    ]
